FROM  nvidia/cuda:10.2-runtime
MAINTAINER paper2code <contact@paper2code.com>

WORKDIR /opt/service

RUN apt-get update && apt-get install -y python3.7 python3.7-dev python3.7-distutils python3-pip curl git

COPY . .

RUN pip3 install neuralqa

EXPOSE 5080

CMD ["neuralqa", "--host", "0.0.0.0", "--port", "5080"]
